theme: jekyll-theme-slate
title: SHU RMRC seminar
description: Sheffield Hallam University Recreational Mathematics Research Cluster seminar

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
